apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/frontend:3.0.0
  imagePullSecrets:
    - name: aws-ecr
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - name: backend
      image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/backend:2.0.0
  imagePullSecrets:
    - name: aws-ecr
