
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::299627189740:role/prod-expense-schema-eks-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema
spec:
  template:
    spec:
      serviceAccountName: schema
      restartPolicy: Never
      initContainers:
      - name: awsparam
        image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/expense-parameter-init-container:2.0.0
        env:
        - name: INPUT
          value: "DBHOST,prod.rds.endpoint DBUSER,prod.rds.master_username DBPASS,prod.rds.master_password"
        volumeMounts:
        - mountPath: /config
          name: config
      containers:
      - name: schema
        image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/expense-schema-load:6.0.6
        env:
        - name: COMPONENT
          value: backend
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        emptyDir:
          sizeLimit: 5Mi
