apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/frontend:5.0.0
  imagePullSecrets:
    - name: aws-ecr
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/backend:5.0.1
      env:
        - name: DB_HOST
          value: mysql
  imagePullSecrets:
    - name: aws-ecr
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema
spec:
  template:
    spec:
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Never
      containers:
        - name: schema
          image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/expense-schema-load:6.0.2
          env:
            - name: DBHOST
              value: prod-mysql.cluster-cmzmzlxo5mcv.us-east-1.rds.amazonaws.com
            - name: DBPASS
              value: "expenseprod1234"
            - name: DBUSER
              value: mysqlrdsadmin
            - name: COMPONENT
              value: backend
