{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-schema
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.appName }}
      restartPolicy: Never
      initContainers:
      - name: awsparam
        image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/expense-parameter-init-container:{{ .Values.initContainers.imageVersion }}
        env:
        - name: INPUT
          value: "{{ .Values.job.INPUT }}"
        volumeMounts:
        - mountPath: /config
          name: config
      containers:
        - name: schema
          image: 299627189740.dkr.ecr.us-east-1.amazonaws.com/expense-schema-load:{{ .Values.job.imageVersion }}
          env:
          - name: COMPONENT
            value: {{ .Values.appName }}
          volumeMounts:
          - mountPath: /config
            name: config
      volumes:
      - name: config
        emptyDir:
          sizeLimit: 5Mi
{{- end }}